config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews

  validates :name, :presence => true

  validates :country, :presence => true

  validates :cost, :presence => true
  validates :cost, numericality: true

  # Not currently working with Faker, booleans still generate
  # validates :featured, :presence

  scope :most_recent, -> {
    order(created_at: :desc)
    .limit(3)
  }

  scope :country_usa, -> {
    where(country: "United States of America")
  }

  scope :most_reviews, -> {(
    select("products.id, products.name, products.country, products.cost, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(10)
  )}

  def self.featured
    where(featured: true)
  end

  def self.not_featured
    where(featured: false)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product

  validates :author, :presence => true

  validates :content_body, :presence => true
  validates :content_body, length: { in: 50..250 }

  validates :rating, :presence => true
  validates :rating, numericality: { only_integer: true }
  validates :rating, :inclusion => 1..5

  validates :product_id, :presence => true
  validates :product_id, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to  products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully removed!"
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :country, :cost, :featured)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review successfully deleted!"
    redirect_to product_path(@review.product)
  end

private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :featured %>
  <%= f.text_field :featured %>
  <%= f.submit  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFoodProduct</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='jumbotron'>
      <h1>Marios Fantastic (Overpriced) Foods</h1>
    </div>
    <div class='container'>
      <% flash.each do |key, value| %>
        <div class='alert alert-info alert-dismissible fade show' role='alert'>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :cost %>(2 digit)
    <%= f.text_field :cost, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :featured %>(boolean)
    <%= f.text_field :featured, :class => "form-control" %>
  </div>
  <%= f.button :Submit, :class => 'btn btn-info' %>
<% end %>

app/views/products/edit.html.erb
<div class='container'>
  <div class='card'>
    <h1 class='card-header'>Edit: <%= @product.name %></h1><br>
    <div class='card-body'>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<%= link_to "New Product", new_product_path %>
  <div class='row'>

    <div class='col col-sm-3'>
      <div class='card'>
        <h2 class="card-header">Most Recently Added Products</h2>
        <% @products.most_recent.each do |product| %>
          <div class='card-body'>
            <p class="card-text">Product: <%= link_to product.name, product_path(product) %></p>
            <p class="card-text">Country of Origin: <%= product.country %></p>
            <p class="card-text">Cost: $<%= product.cost %>.00</p>
            <br>
            <hr>
          </div>
        <% end %>
      </div>
    </div>

    <div class='col col-sm-3'>
      <div class='card'>
        <h2 class="card-header">Products From the U.S. of A.</h2>
        <% @products.country_usa.each do |product| %>
          <div class='card-body'>
            <p class="card-text">Product: <%= link_to product.name, product_path(product) %></p>
            <p class="card-text">Country of Origin: <%= product.country %></p>
            <p class="card-text">Cost: $<%= product.cost %>.00</p>
            <br>
            <hr>
          </div>
        <% end %>
      </div>
    </div>

    <div class='col col-sm-3'>
      <div class='card'>
        <h2 class="card-header">Products With the Most Reviews</h2>
        <% @products.most_reviews.each do |product| %>
          <div class='card-body'>
            <p class="card-text">Product: <%= link_to product.name, product_path(product) %></p>
            <p class="card-text">Country of Origin: <%= product.country %></p>
            <p class="card-text">Cost: $<%= product.cost %>.00</p>
            <br>
            <hr>
          </div>
        <% end %>
      </div>
    </div>

    <div class='col col-sm-3'>
      <div class='card'>
        <h2 class="card-header">Currently Featured Products</h2>
        <% @products.featured().each do |product| %>
          <div class='card-body'>
            <p class="card-text">Product: <%= link_to product.name, product_path(product) %></p>
            <p class="card-text">Country of Origin: <%= product.country %></p>
            <p class="card-text">Cost: $<%= product.cost %>.00</p>
            <br>
            <hr>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/products/new.html.erb
  <div class='card'>
    <h1 class='card-header'>New Product</h1><br>
    <div class='card-body'>
      <%= render "form" %>
    </div>
  </div>

app/views/products/show.html.erb
  <div class='card card-body'>
    <h2>Product: <%= @product.name %></h2>
    <hr>
    <h3>Country: <%= @product.country %></h3>
    <h3>Cost: $<%= @product.cost %>.00</h3>
    <h3>Featured: <%= @product.featured %></h3>
    <p><%= link_to "Edit", edit_product_path(@product) %></p>
    <p><%= link_to "Delete", product_path(@product),
      :data => {:confirm => "You sure?",
      :method => "delete"} %>
    </p>
    <p><%= link_to "Add a Review", new_product_review_path(@product) %></p>
    <p><%= link_to "Return to Products List", products_path %></p>
  </div><br>

  <div class='card'>
    <% if @product.reviews.any? %>
      <h2 class='card-header'>Here are the reviews for this product:</h2>

      <div class='card-body'>
        <% @product.reviews.each do |review| %>
          <p>Author: <%= review.author %></p>
          <p>Review: <%= review.content_body %></p>
          <p>Rating: <%= review.rating %></p>
          <p><%= link_to "Edit", edit_product_review_path(@product, review) %></p>
          <p><%= link_to "Delete Review", product_review_path(@product, review),
            :data => {:confirm => "Are you sure?",
            :method => "delete"} %>
          </p>
        <hr>
        <% end %>
        <% else %>
          <p>There are no reviews yet!</p>
        <% end %>
      </div>
  </div>

app/views/reviews/_form.html.erb
  <%= render('layouts/errors', :object => @review) %>

  <%= form_for [@product, @review] do |f| %>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content_body %>
    <%= f.text_field :content_body, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rating %>
    <%= f.text_field :rating, :class => "form-control" %>
  </div>
    <%= f.button :Submit, :class => 'btn btn-info' %>
  <% end %>

app/views/reviews/edit.html.erb
  <div class='card'>
    <h1 class='card-header'>Edit Review for: <%= @product.name %></h1>
    <div class='card-body'>
      <%= render "form" %>
    </div>
  </div>

app/views/reviews/new.html.erb
  <div class='card'>
    <h1 class='card-header'>New review for <%= @product.name %></h1>
    <div class='card-body'>
      <%= render "form" %>
    </div>
  </div>